Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64" # Latest stable Debian release
  config.vm.provider "virtualbox" do |v|
    v.cpus = 1 # Minumum 2 CPUs for K3s server
    v.memory = 1024 # Minimum 2GB RAM for K3s server
  end
  # VM serveur
  config.vm.define "tcosseS" do |serveur|
    serveur.vm.hostname = "tcosseS"
    serveur.vm.network "private_network", ip: "192.168.56.110"

    serveur.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get install -y curl
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --bind-address=192.168.56.110 --advertise-address=192.168.56.110" sh -
      mkdir -p /vagrant/shared
      cp /var/lib/rancher/k3s/server/node-token /vagrant/shared/token
      chmod 644 /etc/rancher/k3s/k3s.yaml
      echo 'export PATH=$PATH:/usr/local/bin' >> /home/vagrant/.bashrc
      echo 'alias k=kubectl' >> /home/vagrant/.bashrc
      chmod 755 /vagrant/scripts/deploy.sh
    SHELL
  end
end