Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64" # Latest stable Debian release
  config.vm.provider "virtualbox" do |v|
    v.cpus = 1 # Minumum 2 CPUs for K3s server
    v.memory = 1024 # Minimum 2GB RAM for K3s server
  end
  # VM serveur
  config.vm.define "tcosseS" do |serveur|
    serveur.vm.hostname = "tcosseS"
    serveur.vm.network "private_network", ip: "192.168.56.110"

    serveur.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get install -y curl
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --bind-address=192.168.56.110 --advertise-address=192.168.56.110" sh -
      mkdir -p /vagrant/shared
      cp /etc/rancher/k3s/k3s.yaml /vagrant/shared/k3s.yaml
      sed -i 's/127.0.0.1/192.168.56.110/g' /vagrant/shared/k3s.yaml
      chmod 644 /vagrant/shared/k3s.yaml
      chmod 644 /etc/rancher/k3s/k3s.yaml
      echo 'export PATH=$PATH:/usr/local/bin' >> /home/vagrant/.bashrc
      echo 'alias k=kubectl' >> /home/vagrant/.bashrc
      cp /var/lib/rancher/k3s/server/node-token /vagrant/shared/token
    SHELL
  end

  # VM worker
  config.vm.define "mtsujiSW" do |worker|
    worker.vm.hostname = "mtsujiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provision "shell", inline: <<-SHELL
      while [ ! -f /vagrant/shared/token ]; do
        echo "En attente du token depuis le serveur..."
        sleep 2
      done
      apt-get update && apt-get install -y curl
      export TOKEN=$(cat /vagrant/shared/token)
      export K3S_AGENT_ARGS="--node-ip=192.168.56.111"
      mkdir /home/vagrant/.kube
      cat /vagrant/shared/k3s.yaml > /home/vagrant/.kube/config
      rm /vagrant/shared/k3s.yaml
      rm /vagrant/shared/token
      echo 'export PATH=$PATH:/usr/local/bin' >> /home/vagrant/.bashrc
      echo 'alias k=kubectl' >> /home/vagrant/.bashrc
      curl -sfL https://get.k3s.io | K3S_URL="https://192.168.56.110:6443" K3S_TOKEN="$TOKEN" sh -s - --server "https://192.168.56.110:6443"
    SHELL
  end
end